

# Appendix



## Folder structure for this course {#folder-structure}

You probably have created a folder for this course somewhere on your computer. In our example, we assume this folder is located here: `C:/Users/yourname/semester2/Module_DAMO` (mentally replace this with your actual path). This course will take place over several weeks, and in each week you will receive or produce various files. We recommend creating a separate folder for each week, and one folder for the case studies, like so:

```
Course Folder (C:\\Users\\yourname\\semester2\\Module_DAMO)
 ¦--week_1                                                
 ¦--week_2                                                
 ¦--week_3                                                
 |--...                                                
 °--case_studies 
```

For the R-exercises we recommend that you create a new RStudio Project each week in subdirectory of the appropriate week. For example, for the first week your folder structure could look like this: 

```
Folder Week 1 (C:\\Users\\yourname\\semester2\\Module_DAMO\\week_1)
 ¦--slides.pdf                                                  
 ¦--my_notes.docx                                               
 ¦--seminar_screenshot.jpg                                      
 °---damo-week1-rexercise                                             
     ¦--damo-week1-rexercise.Rproj                                   
     ¦--test.csv                                      
     °--my_solution.qmd   
```

Note: 

- the RStudio Project is located in a subfolder of `C:/Users/yourname/semester1/Module_DAMO/week_1` and named `damo-week1-rexercise`.
- `damo-week1-rexercise` is the project's *directory name* and the *project name*
- we realize that `damo` and the week number is redundant, there is a reason[^redundancy] for this
- this means each week is a fresh start (which has pros and cons)

[^redundancy]: You will see the project names of all your RStudio Projects listed in RStudio. Having the week number in the project name keeps you from getting confused on which project you are working on.


## Input: Libraries / packages

Libraries (aka packages) are are "extensions" to the basic R functionality. 
R packages have become indispensable to using R. The vast majority of packages are hosted on [CRAN](https://cran.r-project.org/) and can be easily installed using `install.packages("packagename")`. This installation is done *once*. To use the library, you must load it into the current R session using `library(packagename)`.


E.g. To import data, we recommend using the `readr` package[^readr]. Install the package using the command `install.package("readr")`. To use the package, load it into the current R session using `library("readr")`. 

If the package installation ends with the following message, this means that the installation failed:

```{.txt}
installation of package ‘blabla’ had non-zero exit status
```

If the package installation ends with the following message, this *usually* means that you misspelled the package name

```{.txt}
Warning message:
package ‘blabla’ is not available for this version of R
```



[^readr]: Advantages of `read_delim` over `read.csv`: <https://stackoverflow.com/a/60374974/4139249>
