---
freeze: false
---

# Welcome {.unnumbered .unlisted}

```{r}
#| echo: false
#| output: false

now <- Sys.time()
attr(now, "tzone") <- "Europe/Zurich"
options(knitr.duplicate.label = "allow")
```

The "Data Analysis and Monitoring" module provides an in-depth overview of the methodological skills required for hands-on research and development in any applied data-related or data-heavy project the Master's level. Students will refine their methodological expertise by examining the different typical phases of data analysis and modelling, starting from data capture and preprocessing the data, through exploratory analysis and predictive modelling, to visualization and communication in the end. They will also acquire the methodological foundations that will underpin the subsequent modules in the MSc CEM programme. The module provides both general methodological skills that cut across disciplines (e.g., scientific theory, computer-aided data processing, and statistics) and specialised knowledge in the context of circular economy. 

The materials required for the R exercises are available here, with demo files, exercises and solutions.

This website was last updated on `r now`.