# Preparation Course {#w0-preparation}

In this course we will be using R and RStudio. We ask you to install and/or update these programs *before* the start of the course, so that we do not loose time once the course starts. In this chapter, we cover the course requirements and some tips on how you should change your RStudio settings. 

```{r}
#| echo: false
#| include: false

library("rversions")
library("lubridate")

rv <- rversions::r_release()
rv

rve <- strsplit(as.character(base::getRversion()), "\\.")[[1]]

rversion_minimal <- function(version_string){
  version_int <- as.integer(strsplit(version_string, "\\.")[[1]])
  paste(version_int[1], ifelse(version_int[2] == 0, version_int[2], version_int[2]-1), 0,sep = ".")
}

heute <- paste(month(Sys.Date(), TRUE, FALSE, "C"), year(Sys.Date()), sep = ", ")
```

## Install R

If you haven't installed R yet, do so now by getting the newest version from [CRAN](https://cran.r-project.org/). 



## Install RStudio

[RStudio](https://posit.co/download/rstudio-desktop/) is the IDE (integrated development environment) we use in our course to interact with R. Download and install it on your computer.


## Configure RStudio{#configure-rstudio}

Now we will set some RStudio Global options. But first, **close all instances of RStudio and restart it (!!!)**. Then go to Tools > Global options. 

- **R General**
  - Deactivate the option "Restore .RData into workspace at startup"
  - Set "Save workspace to .RData on exit " to "Never"
- **Code**
  - Activate the option "Use native pipe operator, |> (requires R 4.1+)"
- **R Markdown**
  - Deactivate the option "Show output inline for all R Markdown documents"


Click on "Ok" to apply the change and close the options menu.



### Create an RStudio *project* for the first week

Create a new *RStudio Project* (File > New Project > New Directory > New Project). 

1. Click on "Browse" and switch to *your equivalent* of the folder `C:/Users/yourname/semester1/Module_DAMO/week_1` (the project we are about to initiate will be be created in a subdirectory of this folder). Click on "open" to confirm the selection
2. In the field "Directory name", type `damo-week1-rexercise`. This will be the name of your RStudio project and it's parent directory.
3. Click on "Create Project"

You are all set!